version: "3.3"
services:
  jenkins:
    container_name: jenkins 
    image: jenkins:jcasc

    restart: on-failure

    networks: 
      - jenkins_nw

    environment:
      - DOCKER_HOST=tcp://localhost:4243
        #- DOCKER_CERT_PATH=/certs/client
        #- DOCKER_TLS_VERIFY=1

    ports:
      - 8000:8000
      - 8080:8080
      - 50000:50000

networks:
  jenkins_nw:
