version: "3.3"
services:
  jenkins:
    container_name: jenkins 
    image: jenkins:jcasc
      #image: jenkins/jenkins:lts-jdk11

    restart: on-failure

    networks: 
      - jenkins_nw

    environment:
      - DOCKER_HOST=tcp://localhost:4243

    ports:
      - 8080:8080
      - 50000:50000

networks:
  jenkins_nw:

