name: CD Backend
on:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  cd-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: aalyth/action-trigger-jenkins-job@main
        with:
          url: ${{ secrets.JENKINS_URL }}
          job: cd-backend
