name: CD Frontend 
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - backend/**

jobs:
  cd-frontend:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: aalyth/action-trigger-jenkins-job@main
        with:
          url: ${{ secrets.JENKINS_URL }}
          job: cd-frontend
