name: CD Frontend 
on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  cd-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: aalyth/action-trigger-jenkins-job@main
        with:
          url: ${{ secrets.JENKINS_URL }}
          job: cd-frontend
