name: CI Frontend 
on:
  push:
    paths:
      - frontend/**

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: aalyth/action-trigger-jenkins-job@main
        with:
          url: ${{ secrets.JENKINS_URL }}
          job: ci_frontend
